# Generated by Django 4.1 on 2022-09-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_rename_assigneddutyactivities_memberassigneddutyactivities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitteddutyreports',
            name='rating',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='submitteddutyreports',
            name='work_status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
