# Generated by Django 4.1 on 2022-08-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recieveddutyreports',
            name='new_subject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
