# Generated by Django 4.1 on 2022-08-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0002_recieveddutyreports_new_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extraworkreport',
            old_name='percentage',
            new_name='percentage_done',
        ),
        migrations.RenameField(
            model_name='extraworkreport',
            old_name='overtime_message',
            new_name='work_status',
        ),
        migrations.RemoveField(
            model_name='extraworkreport',
            name='overtime_file',
        ),
        migrations.AddField(
            model_name='assigneddutyactivities',
            name='report_status',
            field=models.CharField(default='Not submitted', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extraworkreport',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extraworkreport',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recieveddutyreports',
            name='overtime_subject',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
