# Generated by Django 4.1 on 2022-09-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0004_assigneddutyactivities_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraworkreport',
            name='extra',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recieveddutyreports',
            name='extra',
            field=models.BooleanField(default=False),
        ),
    ]
